In [1]:
import os
os.chdir(r"C:\Users\gonca\Documents\GitHub\Portefolio_SI\src")

from iobla.csv_file import read_csv
from data.dataset import Dataset
import numpy as np

# Aula 1

In [2]:
# 1.1
dataset = read_csv(r"..\datasets\iris\iris.csv", sep = ",", features = "True", label = True)
dataset2 = read_csv(r"..\datasets\iris\iris_missing_data.csv", sep = ",", features = "True", label = True)

In [5]:
# 1.2
len(dataset.X[:, -2])

150

In [6]:
# 1.3
temp = dataset.X[-10: , : ]
Dataset(temp).get_mean()

array([6.45, 3.03, 5.33, 2.17])

In [7]:
#1.4 
temp = dataset.X <= 6  
final = dataset.X[np.all(temp, axis=1)] 
final.shape[0]

89

In [15]:
# 1.5
dataset.X[dataset.y != 'Iris-setosa'].shape[0]

100

In [59]:
#2.1
from data.dataset import *

print("Iris dataset:", dataset.X.shape)
print("Iris_missing dataset", dataset2.X.shape)
print()
print("......... dropna being applied to both datasets ........")
dataset.dropna()
dataset2.dropna()
print()
print("Iris dataset after dropna method:", dataset.X.shape)
print("Iris_missing dataset after dropna method:", dataset2.X.shape)

Iris dataset: (150, 4)
Iris_missing dataset (150, 4)

......... dropna being applied to both datasets ........

Iris dataset after dropna method: (150, 4)
Iris_missing dataset after dropna method: (134, 4)


In [61]:
# 2.2
print("Nº de valores nulos no Iris dataset:", np.sum(np.isnan(dataset.X)))
print("Nº de valores nulos no Iris_missing dataset", np.sum(np.isnan(dataset2.X)))
print()
print("......... fillna being applied to both datasets using the mean ........")
dataset.fillna("mean")
dataset2.fillna("mean")
print()
print("Nº de valores nulos no Iris dataset Iris dataset after fillna method:", np.sum(np.isnan(dataset.X)))
print("Nº de valores nulos no Iris dataset Iris_missing dataset after fillna method:", np.sum(np.isnan(dataset2.X)))

Nº de valores nulos no Iris dataset: 0
Nº de valores nulos no Iris_missing dataset 17

......... fillna being applied to both datasets using the mean ........

Nº de valores nulos no Iris dataset Iris dataset after fillna method: 0
Nº de valores nulos no Iris dataset Iris_missing dataset after fillna method: 0


In [66]:
#2.3 
print("Iris dataset:", dataset.X.shape)
print("Iris dataset sample 1:", dataset.X[0])
print("Iris dataset sample 2:", dataset.X[1])
print()
print("......... remove_by_index being applied ........")
print()
dataset.remove_by_index(0)
print("Iris dataset after remove_by_index:", dataset.X.shape)
print("Iris dataset new sample 1:", dataset.X[0])

Iris dataset: (150, 4)
Iris dataset sample 1: [5.1 3.5 1.4 0.2]
Iris dataset sample 2: [4.9 3.  1.4 0.2]

......... remove_by_index being applied ........

Iris dataset after remove_by_index: (149, 4)
Iris dataset new sample 1: [4.9 3.  1.4 0.2]


# Aula 2

In [96]:
from feature_selection.select_k_best import SelectKBest
from feature_selection.variance_threshold import VarianceThreshold
from feature_selection.select_percentile import SelectPercentile
from statisticsbla.f_classification import f_classification

In [97]:
#3.3
print("dataset intial features:", dataset.features)
print()
print("Initializing SelectPercentile with 50% and f_classification")
selector = SelectPercentile(f_classification, percentile=50)
selector = selector.fit(dataset)
print()
print(".............. Calculating scores .............")
print(selector.F)
print(selector.p)
print()
new_dataset = selector.transform(dataset)
print(".............. Transforming dataset .............")
selector.fit_transform(new_dataset)
print("Transformed dataset features:", new_dataset.features)

dataset intial features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

Initializing SelectPercentile with 50% and f_classification

.............. Calculating scores .............
[ 119.26450218   47.3644614  1179.0343277   959.32440573]
[1.66966919e-31 1.32791652e-16 3.05197580e-91 4.37695696e-85]

.............. Transforming dataset .............
Transformed dataset features: ['petal_length', 'petal_width']


# Aula 3

In [ ]:
# 4.
# manhattan_distance.py

In [6]:
# 5.2
print(" --> My PCA implementation:")
print()
from decomposition.pca import PCA
pca = PCA(n_components=3)
pca.fit_transform(dataset.X)
print("Explained variance:", pca.explained_variance)
print()
print("Explained variance ratio:", pca.explained_variance_ratio)
print()
print("Components:", pca.components)

from sklearn.decomposition import PCA as sklearnpca
print()
print("---------------------------------------------------------------------")
print(" --> SKlearn PCA:")
SKlearn_pca = sklearnpca(n_components=3)
SKlearn_pca.fit(dataset.X)
print()
print("Explained variance:", SKlearn_pca.explained_variance_)
print()
print("Explained variance ratio:", SKlearn_pca.explained_variance_ratio_)
print()
print("Components:", SKlearn_pca.components_)



 --> My PCA implementation:

Explained variance: [4.19667516 0.24062861 0.07800042]

Explained variance ratio: [0.92461621 0.05301557 0.01718514]

Components: [[ 0.36158968 -0.65653988  0.58099728]
 [-0.08226889 -0.72971237 -0.59641809]
 [ 0.85657211  0.1757674  -0.07252408]
 [ 0.35884393  0.07470647 -0.54906091]]

---------------------------------------------------------------------
 --> SKlearn PCA:

Explained variance: [4.22484077 0.24224357 0.07852391]

Explained variance ratio: [0.92461621 0.05301557 0.01718514]

Components: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]
 [-0.58099728  0.59641809  0.07252408  0.54906091]]


# Aula 4 

In [12]:
# 6.2 - Implementing stratified splitting

from model_selection.split import train_test_split
from model_selection.stratified_train_test_split import stratified_train_test_split

dataset_train, dataset_test = train_test_split(dataset, test_size=0.2, random_state=50)
print("................ Splitting the Iris dataset (train) ...........................")
print()
print("Number of samples belonging to the 3 different classes:")
print("Iris-setosa:", np.sum(dataset_train.y == "Iris-setosa"))
print("Iris-versicolor:", np.sum(dataset_train.y == "Iris-versicolor"))
print("Iris-virginica:", np.sum(dataset_train.y == "Iris-virginica"))
print()

dataset_train1, dataset_test1 = stratified_train_test_split(dataset, test_size=0.2, random_state=50)
print("................ Splitting the Iris dataset using stratified splitting (train) ..............................")
print()
print("Number of samples belonging to the 3 different classes:")
print("Iris-setosa:", np.sum(dataset_train1.y == "Iris-setosa"))
print("Iris-versicolor:", np.sum(dataset_train1.y == "Iris-versicolor"))
print("Iris-virginica:", np.sum(dataset_train1.y == "Iris-virginica"))

print()

print("................ Splitting the Iris dataset (test) ...........................")
print()
print("Number of samples belonging to the 3 different classes:")
print("Iris-setosa:", np.sum(dataset_test.y == "Iris-setosa"))
print("Iris-versicolor:", np.sum(dataset_test.y == "Iris-versicolor"))
print("Iris-virginica:", np.sum(dataset_test.y == "Iris-virginica"))
print()

dataset_train1, dataset_test1 = stratified_train_test_split(dataset, test_size=0.2, random_state=50)
print("................ Splitting the Iris dataset using stratified splitting (test) ..............................")
print()
print("Number of samples belonging to the 3 different classes:")
print("Iris-setosa:", np.sum(dataset_test1.y == "Iris-setosa"))
print("Iris-versicolor:", np.sum(dataset_test1.y == "Iris-versicolor"))
print("Iris-virginica:", np.sum(dataset_test1.y == "Iris-virginica"))

................ Splitting the Iris dataset (train) ...........................

Number of samples belonging to the 3 different classes:
Iris-setosa: 41
Iris-versicolor: 38
Iris-virginica: 41

................ Splitting the Iris dataset using stratified splitting (train) ..............................

Number of samples belonging to the 3 different classes:
Iris-setosa: 40
Iris-versicolor: 40
Iris-virginica: 40

................ Splitting the Iris dataset (test) ...........................

Number of samples belonging to the 3 different classes:
Iris-setosa: 9
Iris-versicolor: 12
Iris-virginica: 9

................ Splitting the Iris dataset using stratified splitting (test) ..............................

Number of samples belonging to the 3 different classes:
Iris-setosa: 10
Iris-versicolor: 10
Iris-virginica: 10


In [ ]:
# 7.1 - Add the RMSE

In [ ]:
# 7.2 - Add the "KNNRegressor" 

In [14]:
# 7.3 - Test the "KNNRegressor" class using the "cpu.csv"

cpu_dataset = read_csv(r"..\datasets\cpu.csv", sep = ",", features = "True", label = True)
from models.knn_regressor import KNNRegressor
from model_selection.split import train_test_split
from sklearn.preprocessing import MinMaxScaler

cpu_dataset_train, cpu_dataset_test = train_test_split(cpu_dataset, test_size=0.2)

knn = KNNRegressor(k=6)

knn.fit(cpu_dataset_train)

score = knn.score(cpu_dataset_test)
print(f'The rmse of the model is: {score}')

The rmse of the model is: (112.46586654719458+0j)


In [75]:
# Optional - Categorical Naïve-Bayes (ver)

from models.categorical_nb import CategoricalNB

n_samples = 1000
n_features = 5

# Generate binary features
X = np.random.choice([0, 1], size=(n_samples, n_features))

# Generate binary labels (0 or 1)
y = np.random.choice([0, 1], size=n_samples)

dataset = Dataset(X, y)

train_data, test_data = train_test_split(dataset, test_size=0.2)

classifier = CategoricalNB(smoothing=1.0)
classifier.fit(train_data)

predictions = classifier.predict(test_data)
accuracy = classifier.score(test_data)

print("Accuracy:", accuracy)

Accuracy: 0.51


# Aula 5

In [ ]:
# test RidgeRegression

In [ ]:
# LogisticRegression

In [ ]:
# 8 - Implementing RidgeRegression with Least Squares

# Aula 7

In [ ]:
# test DecisionTreeClassifier


In [ ]:
# 9.1 - Implementing the RandomForestClassifier class

In [ ]:
# 9.2 - Test the random forest

In [ ]:
# 10.1 - Implementing the StackingClassifier ensemble

In [ ]:
# 10.2 - Test the StackingClassifier

In [ ]:
# Test the k_fold_cross_validation u

In [ ]:
# Test the grid_search_cv

In [ ]:
# 11.1 - Implementing the randomized_search_cv

In [ ]:
# 11.2 - Test the randomized_search_cv

# Aula 9

In [3]:
import numpy as np
from neural_networks.layers import *
from neural_networks.optimizers import *
from neural_networks.losses import *
from metrics import accuracy
from neural_networks.neural_network import NeuralNetwork
from neural_networks.activation import *